public struct PJThemeSD {
    public static let theme = ThemeSD(border: nil,
                                      color: PJThemeSD.makeColor(),
                                      elevation: nil,
                                      font: nil,
                                      size: nil)

    private static func makeColor() -> ThemeColorSD {
        let color = ThemeColorSD(brandPrimary: DesignSystemColorValue.PJ.brandPrimary.uiColor,
                                 brandSecondaryBurgundy: DesignSystemColorValue.PJ.brandSecondaryBurgundy.uiColor,
                                 brandSecondaryYellow: DesignSystemColorValue.PJ.brandSecondaryYellow.uiColor,
                                 bgDark: DesignSystemColorValue.PJ.bgDark.uiColor,
                                 bgLightNeutral: DesignSystemColorValue.PJ.bgLightNeutral.uiColor,
                                 bgLightWhite: DesignSystemColorValue.PJ.bgLightWhite.uiColor,
                                 bgLightYellow: DesignSystemColorValue.PJ.bgLightYellow.uiColor,
                                 neutral30: DesignSystemColorValue.PJ.neutral30.uiColor,
                                 neutral40: DesignSystemColorValue.PJ.neutral40.uiColor,
                                 neutral50: DesignSystemColorValue.PJ.neutral50.uiColor,
                                 neutral70: DesignSystemColorValue.PJ.neutral70.uiColor,
                                 neutral90: DesignSystemColorValue.PJ.neutral90.uiColor,
                                 actionLightPrimaryMain: DesignSystemColorValue.PJ.actionLightPrimaryMain.uiColor,
                                 actionLightPrimaryAuxiliary: DesignSystemColorValue.PJ.actionLightPrimaryAuxiliary.uiColor,
                                 actionLightPrimaryState: DesignSystemColorValue.PJ.actionLightPrimaryState.uiColor,
                                 actionDarkPrimaryMain: DesignSystemColorValue.PJ.actionDarkPrimaryMain.uiColor,
                                 actionDarkPrimaryAuxiliary: DesignSystemColorValue.PJ.actionDarkPrimaryAuxiliary.uiColor,
                                 actionDarkPrimaryState: DesignSystemColorValue.PJ.actionDarkPrimaryState.uiColor,
                                 actionLightSecondaryMain: DesignSystemColorValue.PJ.actionLightSecondaryMain.uiColor,
                                 actionLightSecondaryAuxiliary: DesignSystemColorValue.PJ.actionLightSecondaryAuxiliary.uiColor,
                                 actionLightSecondaryState: DesignSystemColorValue.PJ.actionLightSecondaryState.uiColor,
                                 actionDarkSecondaryMain: DesignSystemColorValue.PJ.actionDarkSecondaryMain.uiColor,
                                 actionDarkSecondaryAuxiliary: DesignSystemColorValue.PJ.actionDarkSecondaryAuxiliary.uiColor,
                                 actionDarkSecondaryState: DesignSystemColorValue.PJ.actionDarkSecondaryState.uiColor,
                                 supportFeedbackAlertDark: DesignSystemColorValue.PJ.supportFeedbackAlertDark.uiColor,
                                 supportFeedbackAlertLight: DesignSystemColorValue.PJ.supportFeedbackAlertLight.uiColor,
                                 supportFeedbackAlertMedium: DesignSystemColorValue.PJ.supportFeedbackAlertMedium.uiColor,
                                 supportFeedbackErrorDark: DesignSystemColorValue.PJ.supportFeedbackErrorDark.uiColor,
                                 supportFeedbackErrorLight: DesignSystemColorValue.PJ.supportFeedbackErrorLight.uiColor,
                                 supportFeedbackErrorMedium: DesignSystemColorValue.PJ.supportFeedbackErrorMedium.uiColor,
                                 supportFeedbackInformationDark: DesignSystemColorValue.PJ.supportFeedbackInformationDark.uiColor,
                                 supportFeedbackInformationLight: DesignSystemColorValue.PJ.supportFeedbackInformationLight.uiColor,
                                 supportFeedbackInformationMedium: DesignSystemColorValue.PJ.supportFeedbackInformationMedium.uiColor,
                                 supportFeedbackSuccessDark: DesignSystemColorValue.PJ.supportFeedbackSuccessDark.uiColor,
                                 supportFeedbackSuccessLight: DesignSystemColorValue.PJ.supportFeedbackSuccessLight.uiColor,
                                 supportFeedbackSuccessMedium: DesignSystemColorValue.PJ.supportFeedbackSuccessMedium.uiColor,
                                 supportBalanceSuccess: DesignSystemColorValue.PJ.supportBalanceSuccess.uiColor,
                                 supportBalanceNegative: DesignSystemColorValue.PJ.supportBalanceNegative.uiColor)
        return color
    }
}
